Changed debug-statehas api
wavesplatform/gowaves pull request #1003
Opened 2023-01-24 08:23 UTC by esuwu

2023-01-25 01:09 UTC, nickeskov requested changes

2023-01-25 01:09 UTC, nickeskov commented on pkg/proto/types.go
> +type StateHashJSDebug struct {
How can I extract `StateHash` struct from this type?

2023-01-25 04:01 UTC, esuwu commented on pkg/api/node_api.go
> +	stateHashDebug := proto.NewStateHashJSDebug(*stateHash, height, a.app.version().Version)
Client library forwards requests to a given URL
What exactly do you think we should update?

2023-01-25 07:30 UTC, alexeykiselev requested changes

2023-01-25 07:30 UTC, alexeykiselev commented on pkg/api/node_api.go
> +	height, err := a.state.Height()
Please reduce the height by 1 with corresponding checks. Scala node doesn't return state hash for the last block (liquid block as they call it) so they return last state hast at height-1.

2023-01-25 07:30 UTC, alexeykiselev commented on pkg/api/node_api.go
> +		return errors.Wrap(err, "failed to get state hash debug")
Please remove error wrap here or replace message with more meaningful "failed to get last state hash".  From this message we can see at what API path error occured.

2023-01-25 09:05 UTC, alexeykiselev requested changes

2023-01-25 09:05 UTC, alexeykiselev commented on pkg/api/node_api.go
> +		return errors.Wrap(err, "failed to the get last state hash")
Message looks wrong :)

2023-01-27 11:14 UTC, alexeykiselev requested changes

2023-01-27 11:14 UTC, alexeykiselev commented on pkg/proto/types.go
>  	Height  uint64 `json:"height"`
Consider adding `omitempty` to height and version fields. What if we request the previous version of node that doesn't support new extended state hash API?

2023-01-30 10:05 UTC, nickeskov approved these changes

2023-01-30 11:00 UTC, alexeykiselev approved these changes

2023-01-30 11:00 UTC, merged