Groth16 update library
wavesplatform/gowaves pull request #1019
Opened 2023-02-08 08:19 UTC by esuwu

2023-03-29 13:55 UTC, alexeykiselev approved these changes

2023-03-29 14:03 UTC, alexeykiselev submitted a review, later dismissed

2023-03-29 22:10 UTC, nickeskov requested changes
I also noticed that `gnark` uses internal logger. I think it should be disabled in our package where we use `gnark`.

2023-03-29 22:10 UTC, nickeskov commented on pkg/crypto/internal/groth16/bls12_381/verifying_key.go
> +	buf := bufio.NewWriter(&b)
I don't see here reasonable usage of this `buf`. You're using `Flush` later, but before I can't find any writes to `buf`.

2023-03-29 22:10 UTC, nickeskov commented on pkg/crypto/internal/groth16/bn256/verifying_key.go
> +	buf := bufio.NewWriter(&b)
I don't see here reasonable usage of this `buf`. You're using `Flush` later, but before I can't find any writes to `buf`.

2023-03-29 22:48 UTC, nickeskov approved these changes

2023-03-30 07:05 UTC, alexeykiselev approved these changes

2023-03-30 07:24 UTC, merged