Node transaction snapshots
wavesplatform/gowaves pull request #1078
Opened 2023-04-19 04:20 UTC by esuwu

2023-06-15 15:06 UTC, nickeskov requested changes

2023-06-20 06:18 UTC, esuwu commented on pkg/state/transaction_performer.go
> +	}
https://github.com/wavesplatform/gowaves/issues/1135

2023-06-26 20:22 UTC, nickeskov requested changes

2023-06-26 20:22 UTC, nickeskov commented on pkg/state/appender.go
> +	}
Please, replace it with `_ = initialSnapshot` and add `TODO`.

2023-06-26 20:23 UTC, nickeskov commented on pkg/state/appender.go
> +	}
And here

2023-06-30 04:15 UTC, merged