change actions count with feature BlockRewardDistribution activated
wavesplatform/gowaves pull request #1088
Opened 2023-05-03 12:21 UTC by Anton-Rampage

2023-05-04 10:29 UTC, alexeykiselev requested changes

2023-05-04 13:29 UTC, alexeykiselev approved these changes

2023-05-05 19:26 UTC, nickeskov commented on pkg/ride/environment.go
> +	isBlockRewardDistributionActivated bool // isBlockRewardDistributionActivated => nodeVersion >= 1.5.0 (TODO:check version node)
Please, fix version in comments.

2023-05-22 14:32 UTC, alexeykiselev approved these changes

2023-05-22 15:13 UTC, merged