Refactoring fsm using a stateless library
wavesplatform/gowaves pull request #1107
Opened 2023-05-24 15:13 UTC by Anton-Rampage

2023-07-18 09:17 UTC, nickeskov requested changes

2023-07-18 09:17 UTC, nickeskov commented on pkg/node/state_fsm/sync_state.go
>  	if p != a.conf.peerSyncWith {
And here

2023-07-31 11:58 UTC, alexeykiselev commented on pkg/node/state_fsm/sync_state.go
> +	if a.conf.peerSyncWith == p {
Outdated

2023-07-31 11:59 UTC, alexeykiselev commented on pkg/node/state_fsm/sync_state.go
>  	if a.conf.peerSyncWith != peer {
Fixed

2023-07-31 11:59 UTC, alexeykiselev commented on pkg/node/state_fsm/sync_state.go
>  	if p != a.conf.peerSyncWith {
Fixed

2023-07-31 12:16 UTC, alexeykiselev commented on pkg/node/state_fsm/fsm_common.go
> +	return func(ctx context.Context, args ...interface{}) (stateless.State, error) {
Fixed

2023-07-31 12:21 UTC, alexeykiselev commented on pkg/node/state_fsm/fsm.go
> +	info.Scheduler.Reschedule()
Fixed

2023-07-31 12:22 UTC, alexeykiselev commented on pkg/node/state_fsm/fsm_common.go
> +		PeerErrorEvent:     {reflect.TypeOf(&Async{}), reflect.TypeOf((*peer.Peer)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()},
Async will be completely removed in a separate PR.

2023-07-31 13:43 UTC, alexeykiselev commented on pkg/node/state_fsm/fsm_common.go
> +	eventsArgsTypes = map[stateless.Trigger][]reflect.Type{
Yes, maybe. Added TODO to consider this for further PR.

2023-07-31 13:46 UTC, alexeykiselev commented on pkg/node/state_fsm/fsm.go
> +	err := f.fsm.Fire(NewPeerEvent, asyncRes, p)
Don't get why to pass context? We don't user context for the FSM, it works in background context entirely.

2023-07-31 13:50 UTC, alexeykiselev commented on pkg/node/node.go
>  		zap.S().Errorf("Failed to : %v", err)
Fixed.

2023-07-31 14:06 UTC, alexeykiselev commented on pkg/node/node.go
>  				zap.S().Warnf("[%s] Unknown info message '%T'", fsm, m)
Already fixed.

2023-07-31 14:23 UTC, alexeykiselev commented on pkg/node/state_fsm/fsm.go
> +	err := f.fsm.Fire(NewPeerEvent, asyncRes, p)
Added TODO

2023-08-17 14:47 UTC, alexeykiselev approved these changes

2023-08-17 15:06 UTC, merged