Set default rate limiter options
wavesplatform/gowaves pull request #1112
Opened 2023-06-01 07:09 UTC by alexeykiselev

2023-06-02 05:55 UTC, nickeskov requested changes

2023-06-05 07:20 UTC, alexeykiselev commented on itests/utilities/common_tx_utility.go
> +	timeout := 50 * time.Millisecond
The idea of this PR is to enable API rate limiter with a quite restrictive settings.
Regarding this timeout, it's a logical retry interval used while waiting for a transaction. In this case it starts from 5ms, and doubles on every iteration up to 1s. It gives us a 9 iterations in the first second. This is quite ok and was changed to 50ms just to set all timeouts to the same value. But in other case it starts from 1ms, and gives us 11 iterations in the first second. This somehow overloads the 100/100 rate limit. 
I'll try to set start interval to 5ms everywhere.

2023-06-05 07:21 UTC, alexeykiselev commented on pkg/api/settings.go
> +func extractFirstIntValue(query url.Values, key string) (int, bool, error) {
Yes, I'll try to do like this.

2023-06-05 07:42 UTC, alexeykiselev commented on cmd/node/node.go
> +		opts.RateLimiterOpts = rlo
Fixed

2023-06-05 10:03 UTC, irina-pereiaslavskaia approved these changes

2023-06-05 10:17 UTC, nickeskov approved these changes

2023-06-05 10:18 UTC, merged