Fixed bug in 'ethereumTransactionToObject' with empty eth tx kind.
wavesplatform/gowaves pull request #1147
Opened 2023-06-29 21:46 UTC by nickeskov

2023-07-03 13:10 UTC, alexeykiselev requested changes

2023-07-03 13:10 UTC, alexeykiselev commented on pkg/ride/tree_evaluation_test.go
>  		withMessageLengthV3().withTransactionObject(obj)
I think better to reimplement builder function `withTransactionObject` and replace it with something like `withTransaction` and hide this environment manipulations  inside of this method.

2023-07-04 01:07 UTC, nickeskov commented
@alexeykiselev Issues has been fixed. Please, review this PR again.

2023-07-04 09:19 UTC, alexeykiselev approved these changes

2023-07-04 09:20 UTC, merged