Replace to snapshot applier
wavesplatform/gowaves pull request #1165
Opened 2023-07-20 22:08 UTC by esuwu

2023-10-11 01:41 UTC, nickeskov requested changes

2023-10-11 01:41 UTC, nickeskov commented on pkg/state/transaction_checker_test.go
> +	snapshotGen := snapshotGenerator{stor: stor.entities, scheme: settings.MainNetSettings.AddressSchemeCharacter}
Use constructor here.

2023-10-29 21:35 UTC, merged

2023-11-05 22:40 UTC, esuwu commented on pkg/state/appender.go
> +	// err = initialSnapshot.Apply(&snapshotApplier)
It is

2023-11-05 22:48 UTC, esuwu commented on pkg/state/transaction_differ_test.go
> +//		to, path := createDifferTestObjects(t, checkerInfo
This function is used for tests. It initializes transaction performer, and transaction performer needs checkerInfo now to initialize snapshot applier

2023-11-06 04:20 UTC, esuwu commented on pkg/state/snapshot_generator.go
> +	}
senderDataEntries is a map, not a slice

2023-11-06 04:21 UTC, esuwu commented on pkg/state/snapshot_generator.go
> +	assetBalanceDiff addressAssetBalanceDiff,
Not relevant anymore

2023-11-06 04:24 UTC, esuwu commented on pkg/state/snapshot_generator.go
> +	resQuantity := assetInf.quantity.Sub(&assetInf.quantity, quantityDiff)
assetInf.quanity has a big.Int type, i wouldn't risk trying to convert a big int number to an int64. I think big.Int is there for a reason

2023-11-06 04:25 UTC, esuwu commented on pkg/state/snapshot_generator.go
> +		sg.generateLeaseAtomicSnapshots(action.LeaseID, *leasingInfo, txID, leasingInfo.Sender, leasingInfo.Recipient, amount)
Not relevant anymore, but also, the validation s in transaction checker

2023-11-06 04:29 UTC, esuwu commented on pkg/state/appender.go
> +	if err = a.diffStor.saveTxDiff(applicationRes.changes.diff); err != nil {
it is not relevant to this PR