Add complexity to snapshots
wavesplatform/gowaves pull request #1210
Opened 2023-09-27 03:15 UTC by esuwu

2023-10-06 13:44 UTC, esuwu commented
This PR shouldn't be merged just yet

2023-10-12 00:44 UTC, nickeskov requested changes

2023-10-12 00:44 UTC, nickeskov commented on pkg/state/snapshot_generator_internal_test.go
> +	}
Maybe move to a function?

2023-10-12 00:44 UTC, nickeskov commented on pkg/state/snapshot_generator_internal_test.go
> +	scriptsBytes, err := base64.StdEncoding.DecodeString(script)
We don't have to store compiled code here. Just use the compiler package and it will create parsed tree from ride script source code.

2023-10-12 00:44 UTC, nickeskov commented on pkg/state/snapshot_generator.go
> +		if scriptEstimation.isPresent() {
You don't have to check `scriptEstimation != nil`. It's equivalent to the `scriptEstimation.isPresent` implementation.
In which case `scriptRecipient` can be `nil`? `InvokeExpression` transaction?

2023-10-12 00:44 UTC, nickeskov commented on pkg/state/snapshot_generator.go
> +		}
`append` works fine with `nil` slices.

2023-10-29 06:02 UTC, esuwu commented
Import is ok on this commit [c10178b](https://github.com/wavesplatform/gowaves/pull/1210/commits/c10178b25cb19ebe72fdefdb9493cd8afe2ab56f)

2023-10-29 21:28 UTC, merged

2023-11-06 04:37 UTC, esuwu commented on pkg/state/snapshot_generator.go
> +		}
it's a map, not a slice