Fix extra issue snapshots
wavesplatform/gowaves pull request #1246
Opened 2023-11-22 00:09 UTC by esuwu

2023-11-24 02:35 UTC, nickeskov requested changes

2023-11-27 09:07 UTC, alexeykiselev approved these changes

2023-11-28 08:43 UTC, nickeskov commented on pkg/state/testdata/scripts/issue_reissue_dapp_snapshots.base64
Not relevant at the moment

2023-11-28 08:43 UTC, nickeskov commented on pkg/state/testdata/scripts/default_dapp_snapshots.base64
Not relevant at the moment

2023-11-28 08:44 UTC, nickeskov approved these changes

2023-11-28 09:13 UTC, merged