Fix 'isNFT' flag initialization for assets
wavesplatform/gowaves pull request #1333
Opened 2024-02-13 15:27 UTC by nickeskov

2024-02-14 08:27 UTC, alexeykiselev requested changes

2024-02-14 08:27 UTC, alexeykiselev commented on pkg/state/assets.go
> +type assetConstInfoRecord struct {
Why keep both types `assetConstInfo` and `assetConstInfoRecord`? May be remove one? Or convert the old one in CBOR record?

2024-02-14 08:27 UTC, alexeykiselev commented on pkg/state/fee_validation.go
> +	quantity   uint64
I think that `int` types were chosen intentionally for better compatibility with Scala implementation.

2024-02-14 08:27 UTC, alexeykiselev commented on pkg/state/fee_validation.go
> -			asset = assetParams{int64(itx.Quantity), int32(itx.Decimals), itx.Reissuable}
May be better to add checks that values fit in `int` types here?

2024-02-15 08:55 UTC, alexeykiselev approved these changes

2024-02-15 09:13 UTC, nickeskov commented
Testnet import on commit [d4a85d0](https://github.com/wavesplatform/gowaves/pull/1333/commits/d4a85d0e6264d064fc98735209aaa94939391523) is ok

2024-02-15 09:22 UTC, alexeykiselev approved these changes

2024-02-15 10:34 UTC, merged