Convert utility rework. Option to sign transactions added.
wavesplatform/gowaves pull request #1420
Opened 2024-05-30 12:00 UTC by alexeykiselev

Option to write or read binary transactions as Base64 strings added.

2024-05-31 03:04 UTC, nickeskov requested changes

2024-05-31 03:04 UTC, nickeskov commented on cmd/convert/main.go
> +func capitalize(str string) string {
Please, add check for empty string case

2024-05-31 10:04 UTC, alexeykiselev commented on cmd/convert/README.md
> +        Output file path.
There is no default value for those options. But they are optional. Ok, I'll clarify it.

2024-05-31 10:05 UTC, alexeykiselev commented on cmd/convert/README.md
> +```bash
The `bash` is used here because it's command line output.

2024-05-31 10:07 UTC, alexeykiselev commented on cmd/convert/README.md
> +./convert -base64 < <Base64 transaction file>
For me it looks redundant. Why invoke `cat` if you can just pass the content of the file?

2024-05-31 20:40 UTC, nickeskov commented on cmd/convert/README.md
> +./convert -base64 < <Base64 transaction file>
Okay, fair enough

2024-05-31 20:41 UTC, nickeskov commented on cmd/convert/config.go
> +func (c *config) close() {
Okay, got it

2024-06-13 17:23 UTC, nickeskov approved these changes

2024-06-13 17:24 UTC, nickeskov approved these changes

2024-06-13 18:29 UTC, merged