Handle challenged blocks
wavesplatform/gowaves pull request #1423
Opened 2024-06-03 09:06 UTC by nickeskov

2024-08-23 08:36 UTC, alexeykiselev requested changes

2024-08-24 20:46 UTC, nickeskov commented on pkg/state/history_storage.go
> +		return nil, err // TODO: end height here is 3236175, so it's throws wrapped io.EOF, i think
Removed

2024-08-24 20:46 UTC, nickeskov commented on pkg/miner/scheduler/scheduler.go
> +	sets *settings.BlockchainSettings,
Changed to `blockchainSettings`

2024-08-24 20:46 UTC, nickeskov commented on pkg/consensus/blocks_validation.go
> +		return errors.Errorf("generator's generating balance is less than required for generation: expected %d, %d",
Fixed

2024-08-27 07:22 UTC, alexeykiselev approved these changes

2024-08-27 07:22 UTC, alexeykiselev approved these changes

2024-08-27 10:35 UTC, merged