added groth16Verify on the bls12-381 curve
wavesplatform/gowaves pull request #358
Opened 2020-09-21 14:05 UTC by esuwu

2020-09-21 15:50 UTC, alexeykiselev requested changes

2020-09-21 15:50 UTC, alexeykiselev commented on pkg/crypto/internal/groth16/bls12381/groth16Verify.go
> +	Proof "github.com/wavesplatform/gowaves/pkg/crypto/internal/groth16/bls12381/proof"
Quote: "When renaming an imported package, the local name should follow the same guidelines as package names (lower case, no under_scores or mixedCaps)" from https://blog.golang.org/package-names.
Why rename if there is no package name collision? If it collides with variable names, like proof in this case, better rename variable to something short, e.g. `proof` to `p`.

2020-09-21 15:50 UTC, alexeykiselev commented on pkg/crypto/internal/groth16/bls12381/proof/proof.go
> +package proof
I think it's better no to separate `proof` and `verificationKey`(wrong naming also), but join them in one package `internal/groth16/bls12-381/` for example, then use renaming to not collide with `kilic/bls12-381`.

2020-09-21 15:50 UTC, alexeykiselev commented on pkg/crypto/internal/groth16/bls12381/verificationKey/verificationKey.go
> +package verificationKey
Move to one package

2020-09-21 15:50 UTC, alexeykiselev commented on pkg/crypto/internal/groth16/bls12381/verifier/verifier.go
> +package verifier
Move

2020-09-22 13:28 UTC, esuwu commented
Benchamarks для 0, 1, 15, 16 inputs. Запускался на i7
<img width="621" alt="Снимок экрана 2020-09-22 в 16 15 54" src="https://user-images.githubusercontent.com/41806871/93888317-86138c00-fcf0-11ea-8a3e-5e012b6bf385.png">

2020-10-12 07:41 UTC, alexeykiselev approved these changes

2020-10-12 07:51 UTC, merged