Ride BigInt support
wavesplatform/gowaves pull request #445
Opened 2021-03-30 15:05 UTC by alexeykiselev

2021-03-30 15:44 UTC, esuwu requested changes

2021-03-30 15:44 UTC, esuwu commented on pkg/ride/math/math.go
> +func checkScales(bs, es, rs int) bool {
leave here a comment about these "bs", "es", "rs" please

2021-03-30 15:44 UTC, esuwu commented on pkg/ride/math/math.go
> +		} else {
we don't need `else` here. You should make `return` just before this line in the end of `if`

2021-03-30 15:44 UTC, esuwu commented on pkg/ride/math/math.go
> +		}
`return`

2021-03-30 15:44 UTC, esuwu commented on pkg/ride/math/math.go
> +	} else {
without `else`

2021-03-30 15:44 UTC, esuwu commented on pkg/ride/math/math.go
> +			r = d.Div(d, two)
`return`

2021-03-30 15:44 UTC, esuwu commented on pkg/ride/math/math.go
> +		} else {
no `else` here

2021-03-30 15:44 UTC, esuwu commented on pkg/ride/math/math.go
> +	s := decimal.WithContext(decimal.Context128).SetMantScale(int64(scale), 0)
put a comment here about `r`, `s` and `m` please

2021-03-30 16:09 UTC, esuwu requested changes

2021-03-31 08:50 UTC, alexeykiselev commented on pkg/ride/functions_bigint.go
> +	if args[0] == nil {
Such function already exists and used, but this copy-paste is intended. Won't fix.

2021-03-31 08:52 UTC, alexeykiselev commented on pkg/ride/functions_bigint.go
> +	i, err := intArg(args)
I don't get you, it's already like this.

2021-03-31 08:54 UTC, alexeykiselev commented on pkg/ride/functions_bigint.go
> +	end := int(offset + size)
No, it's not about precision, it's about slicing bytes in rideBytes.

2021-03-31 09:08 UTC, alexeykiselev commented on pkg/ride/functions_bigint.go
> +	max := items[0]
Yep

2021-03-31 22:38 UTC, esuwu requested changes

2021-03-31 22:38 UTC, esuwu commented on pkg/ride/functions_bigint.go
> +	i, err := intArg(args)
sorry, missed it

2021-03-31 22:38 UTC, esuwu commented on pkg/ride/functions_bigint.go
> +	p := v.Mul(v, n)
leave a comment here

2021-03-31 22:38 UTC, esuwu commented on pkg/ride/functions_bigint.go
> +	} else {
don't need `else` here

2021-03-31 22:38 UTC, esuwu commented on pkg/ride/math/math.go
> +	return baseScale >= 0 && baseScale <= 18 && exponentScale >= 0 && exponentScale <= 18 && resultScale >= 0 && resultScale <= 18
magic constants

2021-03-31 22:42 UTC, esuwu commented on pkg/ride/functions_bigint.go
> +	if args[0] == nil {
then why wouldn't you use it?

2021-03-31 22:47 UTC, esuwu commented
still need variables with the right name especially for those ones `18`, `8`, `511`,  maybe for `0x80` as well

2021-03-31 22:50 UTC, esuwu approved these changes

2021-04-02 09:38 UTC, merged