Invoke expression tx
wavesplatform/gowaves pull request #629
Opened 2021-12-19 10:27 UTC by esuwu

2022-01-26 17:06 UTC, nickeskov requested changes

2022-01-26 17:06 UTC, nickeskov commented on pkg/state/state.go
> +	// Check and perform block's transactions, create balance diffs, write transactions to storage.\
Remove trailing backslash

2022-01-27 09:27 UTC, nickeskov requested changes

2022-01-27 09:27 UTC, nickeskov commented on pkg/proto/invoke_expression_transaction.go
> +package proto
Delete this file and move content to `pkg/proto/transactions_with_proofs.go`.

2022-01-27 09:55 UTC, esuwu commented on pkg/ride/converters.go
> +		}
Actually, I did not. The only difference between version 5 and 6 is that in version 6 there are two fields `originCaller` and `originCaller`. And there is:
```
	if rideVersion >= 5 {
		r["originCaller"] = rideAddress(sender)
		r["originCallerPublicKey"] = callerPK
	}
```

2022-01-27 09:56 UTC, esuwu commented on pkg/proto/invoke_expression_transaction.go
> +func (tx *InvokeExpressionTransactionWithProofs) Validate(scheme Scheme) (Transaction, error) {
I don't think that this check `if tx.Type != InvokeExpressionTransaction` is relevant, as the type of transaction has been filled when initialized.

2022-01-27 10:46 UTC, nickeskov commented on pkg/proto/invoke_expression_transaction.go
> +func (tx *InvokeExpressionTransactionWithProofs) Validate(scheme Scheme) (Transaction, error) {
Yep, you're right. But I think second check is still relevant.

2022-01-27 10:49 UTC, nickeskov commented on pkg/ride/converters.go
> +		}
I'm talking about payments, not `originCaller` and `originCallerPublicKey`.  🙂

2022-01-27 10:55 UTC, esuwu commented on pkg/state/invoke_applier.go
> +		if sender == *scriptAddr && !isInvokeExpression {
This is not only about `InvokeExpression`. In this function, InvokeScript is also handled.

2022-01-27 11:35 UTC, nickeskov commented on pkg/state/invoke_applier.go
> +		if sender == *scriptAddr && !isInvokeExpression {
I'm talking only about `isInvokeExpression` flag. It's redundant.

2022-01-27 13:56 UTC, nickeskov approved these changes

2022-01-27 14:06 UTC, merged