Added dynamic fee in SetScriptTransaction
wavesplatform/gowaves pull request #724
Opened 2022-04-28 16:38 UTC by Anton-Rampage

2022-04-29 08:13 UTC, alexeykiselev commented on pkg/state/fee_validation.go
> +var SetScriptTransactionV6Fee uint64 = 1
May be change to `const`

2022-04-29 08:31 UTC, alexeykiselev commented on pkg/state/fee_validation_test.go
> +
Please, add test on zero bytes script, it's a valid use case, setting empty script removes script from account. According to scala implementations setting zero size script should
cost 1 fee unit.

2022-04-29 12:33 UTC, alexeykiselev approved these changes

2022-04-30 18:01 UTC, nickeskov requested changes

2022-04-30 18:01 UTC, nickeskov commented on pkg/state/fee_validation.go
> +		}
Actually, this check is redundant. Length can't physically be lower than zero.

2022-05-02 15:56 UTC, nickeskov approved these changes

2022-05-04 07:16 UTC, merged