Add exclude list for fsm
wavesplatform/gowaves pull request #747
Opened 2022-05-23 08:02 UTC by Anton-Rampage

2022-05-23 18:33 UTC, esuwu submitted a review, later dismissed

2022-05-27 08:10 UTC, alexeykiselev requested changes

2022-05-27 08:10 UTC, alexeykiselev commented on pkg/node/state_fsm/fsm_sync.go
> +		proto.ContentIDGetBlock,
GetBlock and GetBlockIds messages should be allowed to enable sync after Protobuf blocks activation.

2022-05-27 08:10 UTC, alexeykiselev commented on pkg/node/state_fsm/fsm_idle.go
> +		proto.ContentIDGetSignatures,
GetSignatures, GetBlock, GetBlockIds messages should be allowed to enable blocks distribution from idling nodes.

2022-05-28 00:35 UTC, nickeskov approved these changes

2022-05-30 09:03 UTC, merged