forbid zero payments in invokes
wavesplatform/gowaves pull request #754
Opened 2022-05-25 14:25 UTC by artemreyt

2022-05-25 18:35 UTC, alexeykiselev submitted a review, later dismissed

2022-05-25 19:18 UTC, nickeskov requested changes

2022-05-26 08:26 UTC, artemreyt commented on pkg/ride/environment.go
> +	}
agree👍

2022-05-26 08:26 UTC, artemreyt commented on pkg/proto/scripting.go
> +			}
agree👍

2022-05-26 08:49 UTC, alexeykiselev approved these changes

2022-05-26 08:49 UTC, alexeykiselev approved these changes

2022-05-26 08:54 UTC, merged