Refactor 'ActionsValidationRestrictions' struct.
wavesplatform/gowaves pull request #813
Opened 2022-07-14 12:00 UTC by nickeskov

Remove 'ScriptAddress' field from 'ActionsValidationRestrictions' struct.
Add 'ActionsValidationRestrictions.Scheme' field initialisation.

2022-07-14 12:22 UTC, nickeskov commented on pkg/proto/actions_validator.go
> -		if action.SenderPK() != nil {
Fixed

2022-07-14 16:11 UTC, artemreyt submitted a review, later dismissed

2022-07-14 20:01 UTC, esuwu commented on pkg/ride/functions_proto.go
> +	address, err := env.state().NewestRecipientToAddress(recipient)
Why did you decide to move setting new address?

2022-07-14 20:12 UTC, esuwu requested changes

2022-07-14 20:12 UTC, esuwu commented on pkg/ride/functions_proto.go
> -	address, err := env.state().NewestRecipientToAddress(recipient)
We need to have script addess be set before applying payments, before the function `getLibVersion` expects to see script address in ws.callee()
So, it's better not to move setting address from here

2022-07-15 09:29 UTC, esuwu submitted a review, later dismissed

2022-07-18 14:30 UTC, merged