Improve blockcmp
wavesplatform/gowaves pull request #821
Opened 2022-07-20 10:22 UTC by alexeykiselev

2022-07-20 22:14 UTC, nickeskov requested changes

2022-07-20 22:14 UTC, nickeskov commented on cmd/blockcmp/internal/entities.go
> +	return fmt.Sprintf(
I think `reflect` can be helpful here.

2022-07-20 22:14 UTC, nickeskov commented on cmd/blockcmp/internal/entities.go
> +	return a.AssetID == b.AssetID && a.Name == b.Name && a.Description == b.Description &&
I think `reflect` can be helpful here.

2022-07-21 13:32 UTC, alexeykiselev commented on cmd/blockcmp/internal/entities.go
> +	return fmt.Sprintf(
May be later

2022-07-21 13:32 UTC, alexeykiselev commented on cmd/blockcmp/internal/entities.go
> +	return a.AssetID == b.AssetID && a.Name == b.Name && a.Description == b.Description &&
May be later :)

2022-07-21 13:33 UTC, nickeskov approved these changes

2022-07-21 13:41 UTC, merged