Issue Transaction Test Suite
wavesplatform/gowaves pull request #874
Opened 2022-08-30 13:28 UTC by irina-pereiaslavskaia

New positive and negative tests for Issue Tx.

2022-09-13 09:20 UTC, nickeskov requested changes

2022-09-13 09:20 UTC, nickeskov commented on itests/issue_transaction_test.go
> +		expectedAssetBalance, _ := strconv.ParseInt(td.Expected["asset balance"], 10, 64)
The same as above.

2022-09-13 09:20 UTC, nickeskov commented on itests/testdata/issue_tx_testdata.go
> +}
You can use `time.Now().UnixMilli()`.
```suggestion
func GetCurrentTimestampInMs() uint64 {
	return uint64(time.Now().UnixMilli())
}
```

2022-09-13 09:20 UTC, nickeskov commented on itests/issue_transaction_test.go
> +	suite.NoError(err, "failed to create proofs from signature")
Use `suite.Require()` for fatal errors.

2022-09-15 08:07 UTC, alexeykiselev requested changes

2022-09-15 14:03 UTC, irina-pereiaslavskaia commented on itests/issue_transaction_test.go
> +	utl "github.com/wavesplatform/gowaves/itests/utilities"
Package was renamed

2022-09-15 14:04 UTC, irina-pereiaslavskaia commented on itests/utilities/issue_tx_utility.go
> +}
This functions were removed

2022-09-15 14:06 UTC, irina-pereiaslavskaia commented on itests/utilities/issue_tx_utility.go
> +func GetAvalibleBalanceInWaves(suite *integration.BaseSuite, address proto.WavesAddress) int64 {
Done

2022-09-15 14:06 UTC, irina-pereiaslavskaia commented on itests/utilities/issue_tx_utility.go
> +	return txIds
Renamed

2022-09-15 14:07 UTC, irina-pereiaslavskaia commented on itests/node_client/node_client.go
> +func (c *NodesClients) WaitForTransaction(t *testing.T, ID *crypto.Digest, timeout time.Duration) (error, error) {
Fix

2022-09-15 14:11 UTC, irina-pereiaslavskaia commented on itests/issue_transaction_test.go
> +		expectedAssetBalance, _ := strconv.ParseInt(td.Expected["asset balance"], 10, 64)
Done

2022-09-15 14:11 UTC, irina-pereiaslavskaia commented on itests/issue_transaction_test.go
> +		expectedAssetBalance, _ := strconv.ParseInt(td.Expected["asset balance"], 10, 64)
Done

2022-09-15 14:12 UTC, irina-pereiaslavskaia commented on itests/testdata/issue_tx_testdata.go
> +}
Done

2022-09-15 14:13 UTC, irina-pereiaslavskaia commented on itests/issue_transaction_test.go
> +	suite.NoError(err, "failed to create proofs from signature")
Done

2022-09-15 14:14 UTC, irina-pereiaslavskaia commented on itests/integration_test.go
> +package integration
Fix

2022-09-15 14:14 UTC, irina-pereiaslavskaia commented on itests/integration_test.go
> +	"github.com/wavesplatform/gowaves/itests/fixtures"
Done

2022-09-15 14:14 UTC, irina-pereiaslavskaia commented on itests/integration_test.go
> +func (suite *SendTxSuite) Test_SendTransaction() {
File was removed.

2022-09-15 14:15 UTC, irina-pereiaslavskaia commented on itests/integration_test.go
> +	suite.Run(t, new(SendTxSuite))
File was removed.

2022-09-15 14:15 UTC, irina-pereiaslavskaia commented on itests/utilities/issue_tx_utility.go
> +package utl
Done

2022-09-15 18:03 UTC, nickeskov commented on itests/utilities/issue_tx_utility.go
> +	time.Sleep(timeout)
Btw, it's ok to have `Sleep` here? Looks like unnecessary slowdown of test. You can wait and range through all in parallel.

2022-09-16 07:35 UTC, irina-pereiaslavskaia commented on itests/issue_transaction_test.go
> +	"strconv"
Done

2022-09-16 10:52 UTC, nickeskov commented on itests/issue_transaction_test.go
> +}
Still need to be fixed

2022-09-16 15:01 UTC, irina-pereiaslavskaia commented on itests/issue_transaction_test.go
> +}
Done

2022-09-16 16:19 UTC, merged