Add ride test env builders
wavesplatform/gowaves pull request #875
Opened 2022-09-01 08:56 UTC by alexeykiselev

2022-09-14 06:33 UTC, esuwu submitted a review, later dismissed

2022-09-16 01:09 UTC, nickeskov requested changes

2022-09-16 09:27 UTC, alexeykiselev commented on pkg/ride/test_helpers_test.go
> +		if addr == acc.address() {
Yes, it was moved here from test's mock

2022-09-16 11:12 UTC, alexeykiselev commented on pkg/ride/test_helpers_test.go
> +	sk  crypto.SecretKey
Why for? It's not used outside of helpers code

2022-09-16 13:06 UTC, nickeskov approved these changes

2022-09-20 08:15 UTC, merged