Issue Transaction API Test Suite
wavesplatform/gowaves pull request #907
Opened 2022-10-05 09:04 UTC by irina-pereiaslavskaia

2022-10-06 03:02 UTC, nickeskov requested changes
Looks good, but there are still some places which can be fixed, improved or explained. And don't forget to fix `TODO`s that I left in code.

2022-10-10 15:07 UTC, irina-pereiaslavskaia commented on itests/issue_transaction_api_test.go
> +	suite.Equalf(0, len(actualTxIds), "IDs: %#v", actualTxIds)
Done

2022-10-12 11:11 UTC, alexeykiselev approved these changes

2022-10-12 16:05 UTC, nickeskov approved these changes

2022-10-12 16:05 UTC, merged