move callee dapp version check in invoke() to the beginning
wavesplatform/gowaves pull request #946
Opened 2022-11-18 16:15 UTC by artemreyt

2022-11-19 03:05 UTC, nickeskov requested changes

2022-11-22 09:45 UTC, artemreyt commented on pkg/ride/functions_proto.go
> +	recipientVer, err := ws.NewestScriptVersionByAddressID(recipient.Address.ID())
done.

2022-11-22 09:46 UTC, artemreyt commented on pkg/ride/functions_proto.go
> +		return nil, UserError.Errorf(
returned to `RuntimeError`

2022-11-23 11:04 UTC, alexeykiselev approved these changes

2022-11-24 00:09 UTC, nickeskov approved these changes

2022-11-24 00:09 UTC, merged